import { richCarouselCard, richMediaCard, richArticleCard } from '../../lib/interactiveKit.js';

export default {
  name: 'rich',
  aliases: ['richresponse'],
  category: 'utility',
  description: 'Test the new rich response components.',
  cooldown: 5000,
  execute: async ({ sock, m, args }) => {
    const type = args[0]?.toLowerCase() || 'carousel';

    if (type === 'carousel') {
      await richCarouselCard(sock, m.from, [
        { title: 'Item 1', text: 'This is the first item.' },
        { title: 'Item 2', text: 'This is the second item.' },
        { title: 'Item 3', text: 'This is the third item.' }
      ], { quoted: m });
    } else if (type === 'media') {
      await richMediaCard(sock, m.from, {
        type: 'image',
        url: 'https://cdn.nekos.life/wallpaper/EU3bZjTsl9Q.png',
        caption: 'This is an inline image with a link.',
        tapLinkUrl: 'https://nexora.dev'
      }, { quoted: m });
    } else if (type === 'article') {
      await richArticleCard(sock, m.from, {
        headerText: 'Nexora AI Update',
        contentText: 'We have just added new rich response components!',
        footerText: 'Nexora Team',
        disclaimerText: 'Generated by AI',
        links: [
          { title: 'Learn More', url: 'https://github.com/boyde1317-byte/baileys', text: 'Check out the fork here' }
        ],
        suggested: ['Show more updates', 'Contact Support']
      }, { quoted: m });
    } else {
      await m.reply('Available types: carousel, media, article');
    }
  }
};
